
import { TopicMap, PersonaMap } from './types';

export const TOPICS: TopicMap = {
  "Ecological Dynamics": "Skills aren't 'owned' by the player; they emerge from the relationship between the athlete and their environment.",
  "Ecological Psychology": "We don't just see objects; we see 'affordances'—opportunities for action based on what our bodies can do.",
  "Dynamical Systems Theory": "Movement is self-organizing; a team or a body finds its own way to solve a problem without a 'master' controller.",
  "Growth Mindset": "Your abilities aren't carved in stone; effort and learning from failure are the only ways to actually get better.",
  "Dreams": "The vision you have for your life before the world tells you what is possible.",
  "Hoop Dreams": "The specific grind of trying to make it out of the neighborhood through the game of basketball.",
  "Temptation": "The constant pull to take the easy way out or go back to habits that don't serve your growth.",
  "Love": "The choice to show up for someone else even when it's difficult or inconvenient.",
  "Lust": "A temporary hunger that often confuses the mind and distracts from real connection.",
  "Heartbreak": "The heavy physical pain of losing a connection you thought would last forever.",
  "Friendship": "Having people who will tell you the truth to your face, even when it hurts.",
  "Family": "The people who are stuck with you, and the work required to keep those bonds healthy.",
  "Outgrowing Friendships": "Personal growth is lonely because you have to leave behind people who refuse to change or get better.",
  "Living in the Moment": "Being fully present where your feet are, instead of living in the past or worrying about the future.",
  "Being True to Yourself": "Be self-aware, rather than a repetitious robot.",
  "Never Forgetting Where You Come From": "Keeping your roots in Montreal or the YMCA runs even when you reach the top.",
  "Your Past": "A library of lessons, not a prison sentence you have to keep serving.",
  "Your Future": "An unwritten book that you create through the opportunities you build today.",
  "The 'Mask' We Wear": "We hide our real struggles to look 'tough,' but pretending to be perfect eventually makes you crack.",
  "Finding Home": "Your identity changes as you move through different places; 'home' is a feeling you build, not just a house.",
  "The Struggle": "The friction required to turn a piece of coal into a diamond.",
  "Rags to Riches": "Moving from makeshift hoops and streetball to a life of stability and success.",
  "The Second Wind": "True resilience is only found at the exact moment you feel like you have nothing left to give.",
  "Growth": "To become a better version of yourself, you must be willing to let your old habits and old identity die.",
  "Regret": "Maturity is learning how to live with the weight of choices you can never go back and change.",
  "NBA Superstars (90s)": "The era of physical dominance and legendary individuals like MJ and Hakeem.",
  "NBA Superstars (00s)": "The era of the 'Iso' and global icons like Kobe and Iverson.",
  "NBA Superstars (Today)": "The era of the 3-point revolution and positionless play.",
  "WNBA Superstars (00s)": "The pioneers like Lisa Leslie and Sheryl Swoopes who built the foundation.",
  "WNBA Superstars (Today)": "The new wave of athletes like A'ja Wilson and Caitlin Clark.",
  "Girl Power": "The strength, intelligence, and resilience of women and girls to lead and succeed.",
  "Street Life": "The harsh reality of growing up in high-crime areas where survival is a daily task.",
  "The Jungle": "The reality that only the most adaptable and focused survive when resources are scarce.",
  "Mindfulness": "The practice of watching your thoughts without letting them control your actions.",
  "Zen Philosophy": "Finding the 'stillness in movement' and accepting things as they are.",
  "Zen Stillness": "Real stillness is not found in a quiet room, but in the middle of a fast-paced game or a chaotic life.",
  "Silence/Stillness": "You must find a way to be calm inside your mind even when the world around you is in total chaos.",
  "Metaphors for Life": "Using things like basketball, nature, or chess to explain the complexities of human existence.",
  "The Wisdom in 'Foolish' Questions": "The most important lessons often come from simple questions asked by those we think we are teaching.",
  "Time is the Only Currency": "The grind for money often steals the very life and time you are trying to pay for.",
  "The 'Auto-Pilot' Trap": "Waking up and just going through the motions every day is not the same thing as actually being alive.",
  "The Weight of 'What If?'": "Peace comes from cutting away old dreams you didn't achieve and loving who you actually are right now.",
  "Legacy": "Real living is living for others; your value is measured by the positive mark notation, not your things.",
  "Gratitude": "You will never be happy with 'more' until you are genuinely happy with what you have right now.",
  "Forgiving Your Parents": "Breaking the cycle of family pressure starts with admitting your parents were just flawed kids who grew up without a map.",
  "Forgiving the Unapologetic": "Letting go of a grudge is a gift you give to your own mental health, not a favor for the person who hurt you.",
  "Generational Trauma": "Breaking the cycle of yelling and pressure is the hardest but most important work a parent can do.",
  "The Debt to Your Younger Self": "You have a responsibility to protect your inner child's right to play, rest, and be happy.",
  "Learning to Say 'No'": "You are not in this world to live up to other people's expectations; protecting your peace is a full-time job.",
  "The Right to Be Heard": "If we don't listen to the thoughts and feelings of children, we lose the chance to build a better future.",
  "Digital Control": "Our devices and social media can build us up, or they can destroy our mental health if we aren't the ones in control.",
  "Social Media vs. Reality": "Comparing your messy daily life to someone else's fake highlight reel will always destroy your joy.",
  "Imposter Syndrome": "There is no 'secret' to being a perfect adult; everyone you look up to is just winging it.",
  "The Cost of Ambition": "Every 'win' in business or status has a hidden price tag involving your time, health, or family.",
  "Losing a Hero": "Realizing your mentors and idols are flawed humans is the first step to becoming your own leader.",
  "Animals": "Survival instincts and the raw nature of the animal kingdom.",
  "Reptiles": "Cold-blooded focus and the ability to adapt to harsh environments.",
  "Dogs": "Loyalty, protection, and unconditional love.",
  "Cats": "Independence, agility, and choosing your own path.",
  "Autobiography": "Telling your own story before someone else tries to tell it for you.",
  "Dedication (RIP)": "Honoring those who paved the way but are no longer here to see the progress.",
  "Learning to Listen": "Real communication only happens when you stop waiting for your turn to speak and actually hear the silence."
};

export const RAPPERS: PersonaMap = {
  "The Street Scholar (Nas)": "[Vocal Profile: Male, Raspy Baritone, Authoritative] [Technique: Multi-syllabic rhymes, Behind-the-beat flow, Spoken-word delivery] [Style: East Coast Hip-Hop, Boom Bap, Storytelling, Lyrical, Gritty]",
  "The Liquid Legend (Krayzie Bone)": "[Vocal Profile: Male, Smooth Tenor, Melodic] [Technique: Double-time triplets, Self-harmonized, Sing-song cadence] [Style: Midwest Hip-Hop, Chopper Style, Melodic Rap, Fast Flow, Harmonies]",
  "The Lyrical Juggernaut (Big Pun)": "[Vocal Profile: Male, Booming, Clear] [Technique: Extreme breath control, Heavy alliteration, Rapid-fire delivery] [Style: Hardcore Hip-Hop, East Coast, Lyrical, Fast Flow, Percussive]",
  "The Vocal Shapeshifter (Kendrick Lamar)": "[Vocal Profile: Male, High Tension, Shapeshifting] [Technique: Voice pitch changes, crying delivery, aggressive bursts] [Style: West Coast Hip-Hop, Jazz Rap, Theatrical, Experimental]",
  "The Pattern Master (King Los)": "[Vocal Profile: Male, Sharp Tenor, Precise] [Technique: Compound rhymes, extreme speed, clear diction] [Style: Freestyle Rap, Chopper, Technical, Fast Flow]",
  "The Abstract Professor (Lupe Fiasco)": "[Vocal Profile: Male, Nasal Tenor, Intellectual] [Technique: Complex metaphors, dense vocabulary, spoken-word influence] [Style: Conscious Hip-Hop, Lyrical, Backpack Rap, Complex]",
  "The Relatable King (J. Cole)": "[Vocal Profile: Male, Warm Baritone, Conversational] [Technique: Clear storytelling, relaxed flow, slight sing-song] [Style: Dreamville Style, Conscious Rap, Storytelling, Humble]",
  "The Poetic Go-Go (Wale)": "[Vocal Profile: Male, Dynamic Tenor, Poetic] [Technique: Spoken word delivery, swing rhythm, emotional articulation] [Style: DC Go-Go, Spoken Word, Hip-Hop Soul, Percussive Flow]",
  "The Platinum Player (Jay-Z - Vol 1)": "[Vocal Profile: Male, Clear Tenor, Punchy] [Technique: Bouncy flow, conversational delivery, rhythmic pocket] [Style: 90s Hip-Hop, Glossy Production, Bouncy Flow, Confident]",
  "The Martian (Lil Wayne)": "[Vocal Profile: Male, High Raspy Tenor, Nasal] [Technique: Heavy vocal fry, stream-of-consciousness flow, melodic slurring] [Style: Dirty South, Trap, Wordplay, Auto-Tune (Light), Chaotic]",
  "The Smooth Operator (Snoop Dogg)": "[Vocal Profile: Male, Nasal Tenor, Silky] [Technique: Behind-the-beat flow, melodic cadence, relaxed delivery] [Style: G-Funk, West Coast, Laid Back, Melodic Flow]"
};

export const SINGERS: PersonaMap = {
  "The Glider (Usher)": "[Vocal Profile: Male, Leggero Tenor, Bright] [Technique: Precise Melisma, Heavy Falsetto usage, Seamless transitions] [Style: Contemporary R&B, Dance-Pop, Athletic Vocals]",
  "The Street Narrator (TQ)": "[Vocal Profile: Male, Deep Baritone, Robotic] [Technique: Talk-singing, Flat pitch delivery, Lazy drawl] [Style: West Coast R&B, G-Funk, Talkbox vibes, Electronic Soul]",
  "The Global Icon (Michael Jackson)": "[Vocal Profile: Male, High Tenor, Breathless] [Technique: Vocal hiccups, Aggressive staccato, rhythmic breathing] [Style: Pop, Funk, Disco, High Energy, Percussive Vocals]",
  "The Soul Warrior (Mary J. Blige)": "[Vocal Profile: Female, Mezzo-Soprano, Powerful] [Technique: Raw delivery, emotional straining, slight rasp] [Style: Hip-Hop Soul, R&B, Emotional, Gritty]",
  "The Conscious Queen (Lauryn Hill)": "[Vocal Profile: Female, Alto, Raspy] [Technique: Rap-singing blend, Soulful runs, conversational phrasing] [Style: Neo-Soul, Hip-Hop, Reggae Fusion, Acoustic R&B]",
  "The Whistle Queen (Mariah Carey)": "[Vocal Profile: Female, Soprano, 5-Octave Range] [Technique: Whistle notes, Airy whispers, Power belting] [Style: Pop R&B, Soul, Ballad, High Technicality]",
  "The Silky Soul (Marvin Gaye)": "[Vocal Profile: Male, Smooth Tenor, Whispery] [Technique: Sotto Voce delivery, Vocal layering, Falsetto transitions] [Style: 70s Soul, Vintage Analog Warmth]",
  "The Memphis High (Al Green)": "[Vocal Profile: Male, High Tenor, Falsetto-heavy] [Technique: Soft attack, emotional squeals, head voice] [Style: High-Pitched Soulful Tenor, Soft Romantic Soul]",
  "The Warm Baritone (Donny Hathaway)": "[Vocal Profile: Male, Deep Baritone, Rich] [Technique: Clear diction, Gospel runs, emotional weight] [Style: Warm Round Baritone, Organic Gospel Influence]",
  "The Velvet Smooth (Luther Vandross)": "[Vocal Profile: Male, Velvet Tenor, Polished] [Technique: Extreme breath control, Long sustained notes, smooth runs] [Style: Velvet Tenor Tone, Sophisticated R&B, Lush Harmonies]",
  "The Neo-Soul Vibe (D'Angelo)": "[Vocal Profile: Male, Smoky Tenor, Relaxed] [Technique: Mumbling, Behind-the-beat, falsetto layering] [Style: Neo-Soul, Mumble-Soul, Laid-Back Groove]",
  "The Deep Crooner (Tyrese)": "[Vocal Profile: Male, Heavy Baritone, Resonant] [Technique: Full chest voice, emotional shouting, raw delivery] [Style: Deep Masculine Baritone, Raw Emotional R&B]",
  "The Rhythm Pony (Ginuwine)": "[Vocal Profile: Male, Tenor, Breathy] [Technique: Staccato flow, audible breathing, rhythmic syncopation] [Style: Sharp Rhythmic Tenor, 90s R&B, Futuristic]",
  "The Retro Funk (Silk Sonic)": "[Vocal Profile: Male, Raspy Tenor, High Energy] [Technique: Gritty shouts, smooth falsetto, ad-lib heavy] [Style: 70s Retro Soul, Funk-Infused, Vintage Brass]",
  "The Southern Grit (Anthony Hamilton)": "[Vocal Profile: Male, Raspy Baritone, Textured] [Technique: Vocal fry, soul shouting, slurred diction] [Style: Southern Soul, Neo-Soul, Gospel-Inflected R&B]",
  "The Diva (Whitney)": "[Vocal Profile: Female, Soprano, Powerhouse] [Technique: Full belt, vibrato heavy, clean diction] [Style: Powerhouse Soprano, Crystalline Tone, High Fidelity]",
  "The Soul Queen (Aretha)": "[Vocal Profile: Female, Powerful Alto, Commanding] [Technique: Gospel runs, call and response, heavy vibrato] [Style: Gospel Soul, Soulful Shouting, Vintage Warmth]",
  "The Growler (Christina)": "[Vocal Profile: Female, Agile Soprano, Aggressive] [Technique: Vocal growls, complex runs, whistle notes] [Style: Powerful Belting Soprano, Soul-Pop, Melismatic Runs]",
  "The Piano Soul (Alicia)": "[Vocal Profile: Female, Husky Mezzo, Raw] [Technique: Emotional cracks, strained belt, spoken intro] [Style: Rhythmic Piano R&B, Organic Live Feel, Raw Texture]",
  "The Island Pop (Rihanna)": "[Vocal Profile: Female, Unique Mezzo, Nasal] [Technique: Unique pronunciation, monotone delivery, vocal fry] [Style: Contemporary R&B, Caribbean Inflection, Hypnotic Pop]",
  "The Ethereal Vibe (SZA)": "[Vocal Profile: Female, Light Soprano, Indie] [Technique: Vowel distortion, soft falsetto, conversational flow] [Style: Cursive Singing, Mumble-Soul, Alt-R&B]",
  "The Soft Touch (Aaliyah)": "[Vocal Profile: Female, Soft Soprano, Breathy] [Technique: Whisper-singing, smooth legato, falsetto] [Style: Angelic Soft Soprano, Minimalist R&B, Futuristic]",
  "The Vocal Bible (Brandy)": "[Vocal Profile: Female, Low Mezzo, Textured] [Technique: Complex harmonies, vocal layering, intricate runs] [Style: Smoky Mezzo-Soprano, Deep Layering, Dark Textured R&B]",
  "The Sweetheart (Ashanti)": "[Vocal Profile: Female, Light Soprano, Sweet] [Technique: Breathy delivery, simple melodies, soft attack] [Style: Sweet Melodic Soprano, Light Airy Hooks, Pop Polish]",
  "The Church Belter (J-Hud)": "[Vocal Profile: Female, Powerhouse Alto, Loud] [Technique: Extreme belting, long sustained notes, gospel runs] [Style: Dramatic Powerhouse Alto, Theatrical Soul, Church-Style Belting]",
  "The Chameleon (Hybrid)": "[Vocal Profile: Male, Smooth Tenor, Agile] [Technique: Rapid-fire triplets, vowel elongation, hybrid singing] [Style: Melodic Hip-Hop, R&B Fusion, Fast Flow, Harmonies]"
};

export const PRODUCERS: PersonaMap = {
  "Quincy Jones": "[Production: Orchestral Pop, Jazz-Fusion, lush strings, complex arrangement]",
  "Babyface": "[Production: 90s R&B, Acoustic Guitar, Smooth Synth Pads, Velvet Texture]",
  "Teddy Riley": "[Production: New Jack Swing, Swing Beat, Orchestra Stabs, Snare-heavy]",
  "Dr. Dre": "[Production: G-Funk, West Coast Hip-Hop, High Sine Synth, P-Funk Bass]",
  "DJ Quik": "[Production: West Coast Funk, Handclaps, Talkbox, Jazzy Piano]",
  "DJ U-Neek": "[Production: Horrorcore, Rapid Hi-Hats, Deep Bass, Eerie Piano]",
  "Noah '40' Shebib": "[Production: Underwater filter, Lo-Fi, Ambient Synths, Muffled Drums]",
  "Boi-1da": "[Production: Trap, Dancehall influence, Hard-hitting Drums, Stadium Anthem]",
  "D'Mile": "[Production: Silk Sonic Vibe, Retro-Soul, Live Bass, Modern Mix]",
  "London on da Track": "[Production: Melodic Trap, Piano Lead, Rolling 808s]",
  "DJ Mustard": "[Production: Ratchet, West Coast Bounce, Minimalist, Clap on 2 and 4]",
  "Metro Boomin": "[Production: Dark Trap, Cinematic, Haunting Melody, Gothic]",
  "Timbaland": "[Production: Futuristic Funk, Beatbox Drums, Stutter effects]",
  "Darkchild": "[Production: Y2K R&B, Pop Polish, Acoustic Guitar Shuffles, Vocal Chops]",
  "Jermaine Dupri": "[Production: Atlanta Bass, Fast Tempo, Party Vibe, Catchy Synth Hook]",
  "Velvet Vic": "[Production: Late Night R&B, Smooth Jazz Keys, Key Modulation]",
  "The Headliner": "[Production: Top 40, Pop-Rap, Pop-R&B, Bright Synthesizers, Catchy Hook]",
  "The Crossover": "[Production: 2000s Hip-Hop/R&B Collab, Hard Drums, Melodic Chorus]",
  "The Idol": "[Production: Dance-Pop, Electronic, High Energy, Commercial Polish]",
  "The Pen Griffey (TrapSoul)": "[Production: TrapSoul, Slowed Trap Drums, Heavy 808s, Chopped and Screwed R&B Sample]",
  "The Boom": "[Production: TrapSoul Boom Bap, Deep 808 Bass, Vintage Soul Loop, Heavy Kick]",
  "The Don": "[Production: 90s Mafioso Rap, Fast Tempo Boom Bap, 70s Funk Loop, Aggressive]",
  "The Concrete Conguero": "[Production: Tribal Hip-Hop, Rolling Conga Loops, Apache Breakbeat, Upright Bass]",
  "The Delta Drifter": "[Production: Blues Rap, Clean Electric Guitar, Rimshots, No Hi-Hats, Minimalist]",
  "The Calle Flow": "[Production: Latin Trap, Reggaeton Bounce, Nylon String Guitar, Trap Hi-Hats]",
  "The Concrete Conductor": "[Production: Cinematic Hip-Hop, Gothic Opera Sample, Heavy Boom Bap Drums, Rain Sounds]",
  "The Havana Maestro": "[Production: Cuban Salsa, Piano Montuno, Heavy Congas, Brass Section, Clave Rhythm]",
  "J Soul": "[Production: 90s Boom Bap, DJ Scratching, Jazz Samples, Dusty Lo-Fi Texture]",
  "Marcus Sterling": "[Production: Chipmunk Soul Sample, Luxury Trap, Heavy 808s]",
  "The Imagineer": "[Production: Broadway Musical, Orchestral, Dynamic Tempo Changes, Storytelling]"
};

export const RHYME_SCHEMES: PersonaMap = {
  // TIER 1: BASICS
  "The Nursery Rhyme (AABB)": "[Rhyme Scheme: AABB. End every two consecutive lines with a perfect rhyme.]",
  "The Standard (ABAB)": "[Rhyme Scheme: ABAB. Alternate rhymes. Line 1 matches Line 3; Line 2 matches Line 4.]",
  "The Sandwich (ABBA)": "[Rhyme Scheme: ABBA. The first and fourth lines rhyme; the middle two lines rhyme with each other.]",

  // TIER 2: TECHNICIAN
  "The Inception (Internal)": "[Constraint: Internal Rhyme. Place rhymes in the middle of lines, not just at the end. Pack the bars.]",
  "The Baton Pass (Chain)": "[Constraint: Chain Rhyme. The last word of Line A must rhyme with the first word of Line B.]",
  "The Machine Gun (Mono-Rhyme)": "[Constraint: Mono-Rhyme. Every single line in this section must end with the same rhyme sound.]",

  // TIER 3: GOD MODE
  "The Big Pun (Multis)": "[Constraint: Multis. Rhyme 3-4 syllable phrases. Match vowel sounds perfectly across the entire bar end.]",
  "The Bender (Broken Rhyme)": "[Technique: Bent Rhyme. Force imperfect rhymes by stretching pronunciation or breaking words across lines.]",

  // TIER 4: THE ARCHITECT
  "The Jigsaw (Mosaic)": "[Technique: Mosaic Rhyme. Rhyme single multi-syllable words with broken phrases. Example: 'Propaganda' / 'Proper gander'.]",
  "The Bookends (Framed)": "[Structure: Framed Rhyme. The first word of Line A rhymes with the first word of Line B. The last word of Line A rhymes with the last word of Line B.]",
  "The Countdown (Climbing)": "[Structure: Climbing Rhyme. Move the rhyme placement earlier in each subsequent line. End -> Middle -> Start.]",

  // TIER 5: ABSTRACT
  "The Doppelgänger (Holorime)": "[Constraint: Holorime. Line A and Line B must sound phonetically identical but use different words. Example: 'Rose array' / 'Rosé ray'.]",
  "The Jay-Z Pivot (Antanaclasis)": "[Technique: Antanaclasis. End consecutive lines with the exact same word, but change the context/meaning of the word each time.]",
  "The Spillover (Across-the-Bar)": "[Flow: Across-the-Bar. Do not stop at line breaks. Carry the sentence and rhyme scheme over into the start of the next measure.]",

  // TIER 6: HIGH CONCEPT
  "The Count (Numerical Progression)": "[Concept: Numerical Progression. Weave the numbers 1 through 10 sequentially into the lyrics. The numbers must be part of the narrative, not just a list.]",
  "The Rewind (Reverse Chronology)": "[Concept: Reverse Chronology. Tell the story backwards. Start with the consequence and end with the cause. Events unfold in reverse time.]",
  "The Possessed (Object POV)": "[Perspective: Anthropomorphism. Write from the perspective of an inanimate object. Describe the physical sensations of being used/played with.]",
  "The ABCs (Alphabet Aerobics)": "[Constraint: Alliteration Progression. Section 1 uses mostly 'A' words. Section 2 uses mostly 'B' words. Progression: A -> B -> C.]",
  "The Hammer (Anaphora)": "[Rhetorical Device: Anaphora. Begin every single line with the exact same phrase. Build intensity with each repetition.]",
  "The Missing Link (No 'I' or 'Me')": "[Constraint: Lipogram. Write this entire verse without using the word 'I', 'Me', or 'My'. Describe personal actions without using first-person pronouns.]",

  "The Jazz Poet (Free Verse)": "[Constraint: No fixed rhyme scheme. Focus on flow and rhythm over end-rhymes.]"
};
